### PR TITLE
Branch fix mh overlap appt

### LINKED ISSUE #225: [PE-D][Tester E] Long names cover up the appointments section
If the patient has a particularly long name, his/her name will cover up the appointments section in the UI. Refer to screenshot below. Consider limiting the length of the name or redesigning the UI such that the name does not cover the appointments section. 

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #235: [PE-D][Tester C] Help command known issue
**Step to reproduce**
1. Type help into the command box
2. Minimise the help window

Image

3. After typing help again, the help window does not pop up again

I understand that this is a known issue, however I believe that it can be fixed in 1 line, you can take a look at it!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #239: [PE-D][Tester D] Help window layout breaks in full-screen: content cramped at bottom-right with huge empty space
In macOS environment, when user launch the app in full screen and open the help window. The Help window fills the screen, but the content is rendered in a small area at the bottom-right with large empty margins (see screenshot). It would be better if help contents are located at the center/left-align of the window and scale responsively to the window size.

Image

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #256: [PE-D][Tester C] GUI overlap between Medical History and Appointment
**Steps to reproduce**
1. Type in "add n/Ng Wei Ming i/S9123456A g/M p/91234567 e/weiming.ng@example.com d/15-03-1985 a/123 Bishan Street 22, # 04-56, Singapore 570123 mh/Hypertension mh/Type 2 Diabetes mh/Seasonal Allergic Rhinitis mh/Mild Asthma childhood onset mh/High Cholesterol Hyperlipidemia mh/History of Gastric Ulcer resolved mh/Chronic Lower Back Pain mh/Eczema intermittent mh/Family history of heart disease mh/Recent knee arthroscopy 2022" into the command box.
2. Type in "add-appt 1 at/Checkup ad/31-10-2025, 1800" into the command box
3. The GUI will look as follow.

Image

I believe that it is reasonable for an elderly patient to have a lot of medical history, and when that is the case, the Medical Record will overlap with the Upcoming Appointment. I think that it is worth fixing this bug.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by jxnwxx**
Fixes #225 
Fixes #235 
Fixes #239
Fixes #256

### CODE REVIEW

File: src/main/java/seedu/address/model/patient/Name.java [hunk 1]
```diff
@@ -10,13 +10,14 @@
...
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphanumeric characters and spaces, and it should not be blank nor exceed 80 "
+                    + "characters.";
 
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
+    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]{0,79}";
```
Comment (WhyisQuek) [inline src/main/java/seedu/address/model/patient/Name.java]: Should this be {1, 80} instead?
